# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='image_category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='image_location',
        ),
    ]
