# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cateory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='lname',
        ),
    ]
