# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190303_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateory',
            new_name='Category',
        ),
    ]
